# Docs for the Azure Functions Deploy action: https://github.com/azure/functions-action

name: Build and deploy dotnet project to Azure Function App - function-skyddsrum

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  DOTNET_VERSION: "10.0.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        shell: bash
        run: |
          pushd "./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          dotnet publish --configuration Release --output ./output
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_78952883DC8340FA9FCF1A0E049028F5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6A587099B890434A83F86DA72162BEF9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6FAF9839EA6748048A497DCAACBFDDEA }}

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: "function-skyddsrum"
          slot-name: "Production"
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
