# Deploys the backend to the Flex Consumption Function App.

name: Deploy backend to function-skydd

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  DOTNET_VERSION: "10.0.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        shell: bash
        run: |
          pushd "./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          dotnet publish Skyddsrum.Functions.csproj --configuration Release --output ./output
          popd

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: "function-skydd"
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
          sku: "flexconsumption"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8ABB300607AA418683992B2F61F1D537 }}
